import { encodeBytes32String, keccak256, toUtf8Bytes } from "ethers";
import type { Address } from "viem";

import {
  importStealthKeys,
  metaAddressFromKeys,
  type Hex,
  type StealthKeys,
  type StealthMetaAddress,
} from "./stealth";

/**
 * Demo mode — a fully populated NullOwn with no chain behind it.
 *
 * ---------------------------------------------------------------------------
 * Why this exists
 * ---------------------------------------------------------------------------
 * A fresh clone has no deployment and no circuit artifacts, so every panel
 * renders its "not configured" state and nothing can be clicked. That is honest
 * but useless for showing the system. With `NEXT_PUBLIC_DEMO_MODE=true` the
 * hooks swap their chain calls for the fixtures below and the whole app becomes
 * clickable end to end.
 *
 * ---------------------------------------------------------------------------
 * What is real and what is not
 * ---------------------------------------------------------------------------
 * Everything cryptographic stays real. Stealth keys are generated by the actual
 * secp256k1 code, announcements are derived with the real ECDH, the Merkle tree
 * is a real Poseidon tree, and the nullifier is the real Poseidon hash — so
 * "Reveal Controlling Key" genuinely re-derives a key that controls the address
 * it claims to.
 *
 * What is fabricated is everything that would otherwise need a chain: contract
 * addresses, block numbers, transaction hashes, the audit log, role
 * assignments, and the Groth16 proof bytes. Those are marked as such wherever
 * they surface.
 *
 * Demo mode is off unless explicitly switched on, and nothing here is imported
 * on a path that runs when it is off.
 */

/** Master switch. Read literally so Next.js can inline it at build time. */
export const demoMode = process.env.NEXT_PUBLIC_DEMO_MODE === "true";

// ---------------------------------------------------------------------------
// Fabricated chain configuration
// ---------------------------------------------------------------------------

/**
 * Addresses that look deliberately synthetic — leading digits spell the
 * standard number or the contract's role — so nobody mistakes a demo screenshot
 * for a real deployment.
 */
export const DEMO_CONTRACT_ADDRESSES = {
  stealthAnnouncer: "0x5564000000000000000000000000000000005564",
  stealthRegistry: "0x6538000000000000000000000000000000006538",
  ownershipVerifier: "0x7e21000000000000000000000000000000007e21",
  complianceModule: "0xc0de00000000000000000000000000000000c0de",
} as const satisfies Record<string, Address>;

/** Sepolia, so explorer links and chain names render as they would in reality. */
export const DEMO_CHAIN_ID = 11155111;

/** Plausible deployment block, used as the scanner's lower bound. */
export const DEMO_START_BLOCK = 7_412_000;

/** Chain head the fake scanner walks up to. */
export const DEMO_LATEST_BLOCK = 7_468_912;

/** The wallet the mock connector reports as connected. */
export const DEMO_ACCOUNT = "0xa11ce0000000000000000000000000000000a11c" as Address;

/** Holder of DEFAULT_ADMIN_ROLE in the demo. Same account, so admin UI shows. */
export const DEMO_ADMIN = DEMO_ACCOUNT;

/** Accounts that start with REGULATOR_ROLE. */
export const DEMO_REGULATORS: readonly Address[] = [
  DEMO_ACCOUNT,
  "0x4e6d1a0000000000000000000000000000004e6d" as Address,
  "0xf1ca5c000000000000000000000000000000f1ca" as Address,
];

/** A counterparty with a registry entry, so the send flow has someone to pay. */
export const DEMO_RECIPIENT = "0xb0b0000000000000000000000000000000000b0b" as Address;

// ---------------------------------------------------------------------------
// Deterministic key material
// ---------------------------------------------------------------------------

/**
 * A 32-byte scalar from a label.
 *
 * keccak of a fixed string gives a stable, valid secp256k1 private key — the
 * chance of landing outside the scalar field is ~2^-128, and `importStealthKeys`
 * would reject it loudly rather than silently misbehave.
 */
function scalarFromSeed(seed: string): Hex {
  return keccak256(toUtf8Bytes(`nullown-demo/${seed}`)) as Hex;
}

/**
 * The stealth keys the demo pretends a given account owns.
 *
 * Derived from the address so every account in the demo has a stable, distinct
 * meta-address — two lookups of the same address always agree, and two
 * different addresses never collide.
 */
export function demoKeysFor(account: string): StealthKeys {
  const lower = account.toLowerCase();
  return importStealthKeys(scalarFromSeed(`spend/${lower}`), scalarFromSeed(`view/${lower}`));
}

/** Registry entry the demo returns for an account with no explicit registration. */
export function demoMetaAddressFor(account: string): StealthMetaAddress {
  return metaAddressFromKeys(demoKeysFor(account));
}

// ---------------------------------------------------------------------------
// Fabricated chain events
// ---------------------------------------------------------------------------

/** A stable 32-byte hash standing in for a transaction hash. */
export function demoTxHash(seed: string): `0x${string}` {
  return keccak256(toUtf8Bytes(`nullown-demo-tx/${seed}`)) as `0x${string}`;
}

/** Block numbers for the fabricated announcements, inside the scanned range. */
export const DEMO_ANNOUNCEMENT_BLOCKS = [7_419_338, 7_441_207, 7_463_990] as const;

/** Accounts credited as having published the fabricated announcements. */
export const DEMO_ANNOUNCERS: readonly Address[] = [
  "0x15500e0000000000000000000000000000001550" as Address,
  DEMO_RECIPIENT,
  "0x7ea50000000000000000000000000000000007ea" as Address,
];

/** How many announcements the fake scan claims to have examined per chunk. */
export const DEMO_ANNOUNCEMENTS_PER_CHUNK = 137;

/** Number of chunks the fake scan walks, purely for the progress bar. */
export const DEMO_SCAN_CHUNKS = 7;

// ---------------------------------------------------------------------------
// Compliance fixtures
// ---------------------------------------------------------------------------

/**
 * Structurally identical to `AuditRecord` in `hooks/useCompliance`. Declared
 * here rather than imported so this module stays free of hook dependencies —
 * the hooks import demo data, never the other way round.
 */
export interface DemoAudit {
  id: number;
  regulator: Address;
  scope: string;
  scopeLabel: string;
  timestamp: number;
  fulfilled: boolean;
  encryptedResponse: string;
}

/** Ciphertext blob — deterministic, meaningless, and obviously not plaintext. */
function demoCiphertext(seed: string, words: number): string {
  let out = "0x";
  for (let i = 0; i < words; i++) {
    out += keccak256(toUtf8Bytes(`nullown-demo-cipher/${seed}/${i}`)).slice(2);
  }
  return out;
}

function auditScope(label: string): { scope: string; scopeLabel: string } {
  return { scope: encodeBytes32String(label), scopeLabel: label };
}

/**
 * A believable audit history: a mix of answered and open requests, from more
 * than one regulator, newest last — `useCompliance` reverses for display.
 */
export const DEMO_AUDITS: readonly DemoAudit[] = [
  {
    id: 0,
    regulator: DEMO_REGULATORS[1]!,
    ...auditScope("EU-MiCA"),
    timestamp: Math.floor(new Date("2026-04-18T09:24:00Z").getTime() / 1000),
    fulfilled: true,
    encryptedResponse: demoCiphertext("audit-0", 3),
  },
  {
    id: 1,
    regulator: DEMO_REGULATORS[2]!,
    ...auditScope("SG-MAS-RWA"),
    timestamp: Math.floor(new Date("2026-05-27T14:02:00Z").getTime() / 1000),
    fulfilled: true,
    encryptedResponse: demoCiphertext("audit-1", 4),
  },
  {
    id: 2,
    regulator: DEMO_REGULATORS[1]!,
    ...auditScope("EU-MiCA-Q2"),
    timestamp: Math.floor(new Date("2026-06-30T11:47:00Z").getTime() / 1000),
    fulfilled: true,
    encryptedResponse: demoCiphertext("audit-2", 2),
  },
  {
    id: 3,
    regulator: DEMO_REGULATORS[2]!,
    ...auditScope("UK-FCA-PROP"),
    timestamp: Math.floor(new Date("2026-07-22T16:15:00Z").getTime() / 1000),
    fulfilled: false,
    encryptedResponse: "0x",
  },
  {
    id: 4,
    regulator: DEMO_REGULATORS[1]!,
    ...auditScope("EU-MiCA-Q3"),
    timestamp: Math.floor(new Date("2026-08-03T08:05:00Z").getTime() / 1000),
    fulfilled: false,
    encryptedResponse: "0x",
  },
];

// ---------------------------------------------------------------------------
// Proving fixtures
// ---------------------------------------------------------------------------

/** Holdings the /prove page starts with, so the form is never empty. */
export const DEMO_HOLDINGS: readonly { tokenId: string; quantity: string }[] = [
  { tokenId: "8801", quantity: "250" },
  { tokenId: "8802", quantity: "1000" },
  { tokenId: "9417", quantity: "12" },
];

/** Threshold pre-filled on /prove — deliberately below the selected holding. */
export const DEMO_THRESHOLD = "100";

/**
 * Groth16 proof points.
 *
 * These are fabricated field elements. They have the right shape for
 * `verifyOwnership` — eight BN254 elements, `[a, b, c]` flattened — and a real
 * verifier would reject them, which is the correct outcome: demo mode never
 * submits them anywhere. The public signals shown next to them are computed for
 * real from the user's own input.
 *
 * Derived from a seed rather than typed out so every element is guaranteed to
 * be inside the scalar field. Truncating to 253 bits is enough: 2^253 - 1 is
 * below the BN254 modulus, so no reduction is needed and this module stays free
 * of the circomlibjs import that `lib/poseidon` carries — `lib/env` reaches
 * this file from the server-rendered layout.
 */
export const DEMO_PROOF_POINTS: readonly bigint[] = Array.from(
  { length: 8 },
  (_unused, index) =>
    BigInt(keccak256(toUtf8Bytes(`nullown-demo-proof/${index}`))) & ((1n << 253n) - 1n),
);

/** Wall-clock proving time the demo reports, in the range a real proof takes. */
export const DEMO_PROVING_TIME_MS = 6_240;

// ---------------------------------------------------------------------------
// Timing
// ---------------------------------------------------------------------------

/** Await a fabricated delay so simulated work does not complete instantly. */
export function demoDelay(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

/** How long a simulated wallet prompt sits in the "confirm in wallet" state. */
export const DEMO_WRITE_MS = 900;

/** How long a simulated transaction sits unconfirmed. */
export const DEMO_CONFIRM_MS = 1_800;
